### PR TITLE
changes moved pull from old branch and update to match backward idam roles compatibility

### PR DESCRIPTION
**Pull request by ATedy**
###backward compatibility for Idam roles ###

### CODE REVIEW

**Comment by ATedy** [comment]
Idam role backward compatibility for Access profiles

**Comment by linusnorton** [comment]
Hey, @ATedy do you have a test for this?

**Comment by ATedy** [comment]
> Hey, @ATedy do you have a test for this?

the second RoleToAccessProfiles.json test data is update to match the changes I did and its passing.

**Comment by ATedy** [comment]
> Hey, @ATedy do you have a test for this?

Yes, just pushed that in

**Review by linusnorton — APPROVED** [review]

**Pull request merged**
