### PR TITLE
St 871

### PR DESCRIPTION
**Pull request by tamir-b**

### CODE REVIEW

**Review by spotstory — COMMENTED** [review]
This change is required to support temporary idam role backwards compatibility whilst a service is transitioning to Access Profiles. It does this by providing a mechanism to optionally prefix individual values in column RoleToAccessProfile:RoleName with "idam:" as per AM guidance (https://tools.hmcts.net/confluence/display/AM/2022-08-09+Access+Management+Configuration)

**Review by spotstory — CHANGES_REQUESTED** [review]
ccd-config-generator/src/main/java/uk/gov/hmcts/ccd/sdk/api/CaseRoleToAccessProfile.java row 60 is failing a style check - it'll need a space before the '{' same as the previous methods.

Please fix and re-submit

**Review by spotstory — CHANGES_REQUESTED** [review]
The test caseRoleToAccessProfile.isLegacyIdamRole() should only be affecting the put of the RoleName field

**Review by spotstory — APPROVED** [review]

**Comment by linusnorton** [comment]
Also please add a test

**Pull request merged**
