### PR TITLE
Added publish flag in Field, for WA configuration in Special Tribunals

### PR DESCRIPTION
**Pull request by ShwetaTandel-hmcts**
Added publish flag in Field, for WA configuration in Special Tribunals

Along with the Event, we need to publish some of the CaseEventFields to the Camunda server.
To facilitate this , we need to expose a publishToCamunda method to be used to set the flag true.

### CODE REVIEW

**Comment by linusnorton** [comment]
@ShwetaTandel-hmcts can you add a test showing example usage?

**Comment by ShwetaTandel-hmcts** [comment]
If my understanding is correct I will have to expose a new method (for eg. mandatoryWithPublishToCamunda , optionalWithPublishToCamunda etc) in FieldCollection to use the flag publishToCamunda from the Field class. Will that affect anything else like Ex UI or any other features which use FieldCollection?

**Comment by linusnorton** [comment]
Is it possible to infer/automate this? Perhaps any field used in an event published to camunda should have the publish field set?

**Comment by ShwetaTandel-hmcts** [comment]
I am trying to achieve this https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1460561625#WorkAllocationPhase2ScopeofDelivery-NewPublishandPublishAsColumnforCaseEventToFields
After talking to few other teams who have done this for WA, I understood that its advised to publish fields only which are needed for that specific event. Curently I dont have a complete list of fields with me , but its not many. 
I was thinking of overloading optional, mandatory methods which will set the flag is passed.

**Review by linusnorton — APPROVED** [review]

**Pull request merged**
